services:
  app-prod:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1

  app-dev:
    build:
      context: .
      target: dev
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src  # Mount source for live reload in dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
